{
 "title": "New1",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "temperature" }
   ]
  },
  {
   "title": "Temperature ( *C)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "temperature" }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "humidity" }
   ]
  },
  {
   "title": "Humidity  ( % )",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    { "expr": "humidity" }
   ]
  },
  {
   "title": "CO2 ppm",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "co2_ppm" }
   ]
  },
  {
   "title": "CO2 (ppm)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "co2_ppm" }
   ]
  },
  {
   "title": "Air Pollution ",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "pm2" }
   ]
  },
  {
   "title": "Air Pollution ",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "pm2" }
   ]
  },
  {
   "title": "Multichannel Gas Sensor",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "co" },
    { "expr": "nh3" },
    { "expr": "no2" },
    { "expr": "c2h5oh" },
    { "expr": "h2" }
   ]
  },
  {
   "title": "Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "co2_ppm" }
   ]
  }
 ]
}